CREATE DATABASE RetailDB;

USE RetailDB;

CREATE TABLE products (
 productId INT PRIMARY KEY AUTO_INCREMENT,
 name VARCHAR(100) NOT NULL,
 category VARCHAR(50) NOT NULL,
 price DOUBLE,
 stockQuantity INT
)

